### ISSUE TITLE
NFA/DFA AutomatonType changes match semantics

### ISSUE THREAD

**Issue by hyperpape** [almondtools/regexbench#3]
For several benchmarks, the number of results depends on whether the AutomatonType is NFA or DFA. With an NFA, the expected matches appear to be the leftmost-first semantics that most languages use, including the Java standard library. With DFA, it appears that the benchmarks are expecting leftmost-longest matches.  

I think this isn't right. Either an NFA or a DFA can implement either type of semantics. I would think that it would be preferable to have a method whereby the Automaton can specify the semantics it uses.

**Comment by almondtools** [comment]
I think you must read the label in an other way: 

It appeared that DFA-based libraries all supported the leftmost-longest matching and NFA-based library all supported the leftmost first. And not every DFA-based library supported leftmost first, while not every NFA-based library supported leftmost-longest.

Do not take me wrong:

I think it is quite suitable, if the tested/benchmarked library (e.g. [patternsearchalgorithm](https://github.com/almondtools/patternsearchalgorithms) does) offers a switch/configuration to specify this. But in fact, not all tested libraries do it and I know of no library with a switch where switching comes with a performance boost. So benchmarking this cases should not add any new information, If I did miss a clever optimization here, let me know.

**Comment by almondtools** [comment]
What about returning NFA?

The benchmark results do not contain this switch. So there are no further consequences.

Another option would be that I rename `AutomatonType` to `SearchType` and the enum variants to `LEFTMOST_FIRST` and `LONGEST_LEFTMOST`.

Yet, leftmost first is misleading, because DFA would just return the matches with increasing length, while NFAs return the matches in a non-deterministic sequence. So DFA and NFA do not have the same conception of "FIRST". Probably "LONGEST_MATCH" and "ALL_OVERLAPPING_MATCHES" would be better ...

**Comment by hyperpape** [comment]
I find the idea of specifying the search semantics/search type independently of the NFA/DFA distinction cleaner. But I certainly can have the NeedleAutomaton return NFA if need be to make test cases pass.

With regard to match semantics, here is how I understand it: leftmost-first means that when the regex processes an alternation (`|`), it prefers to match the first option if possible. So searching for  `(ab|a|bc)` in `"abc"`, we match `ab` then fail to match any more. If the regex were `(ab|a|bc)bc`, it would return `"abc"`, taking the second option from the alternation, because that's the only way to find a matching substring. This is often described as backtracking, but that's an implementation detail--a non-backtracking engine can return the same results.

Leftmost-longest means that the engine returns whatever the longest match is at the starting point. So `(ab|a|bc)` returns the entire string `"abc"`. 

You can also write an implementation that returns `"a"`, `"ab"`, `"bc"`, `"abc"` in some order, and some engines support this option, but I don't think it's the behavior of the standard library, and is just a third option. 

Some things I'm drawing on here: 
https://docs.rs/aho-corasick/latest/aho_corasick/enum.MatchKind.html

I also found this while searching today, though it does seem slightly different: https://github.com/rust-lang/regex/blob/10fe722a3fcfdc17068b21f3262189cc52227bb5/regex-automata/src/util/search.rs#L1698

**Comment by almondtools** [comment]
> I find the idea of specifying the search semantics/search type independently of the NFA/DFA distinction cleaner. But I certainly can have the NeedleAutomaton return NFA if need be to make test cases pass.

So you want to have two Dimensions:
- Search Semantics (NFA,DFA)
- Search Type (LONGEST, FIRST)

But for which purpose would you need NFA, DFA then?

So my conclusion would be: Just replace Search Semantics by Search Type and use the correct names. Yet I am not certain if I got you.

> This is often described as backtracking, but that's an implementation detail--a non-backtracking engine can return the same results.

It think that a DFA gets strictly more complex to support the same leftmost-first as a backtracking NFA. Did you do this with needle?

**Comment by hyperpape** [comment]
I didn't know if you wanted the NFA/DFA methods for some purpose in displaying output or anything else, so I didn't suggest to remove them. If you don't think they serve any other purpose, then replacing them entirely with a method specifying the desired search semantics makes sense to me.

**Comment by almondtools** [comment]
Have a look at the upper commit. I think the meaning of `SearchType` is clearer now. Can this issue be closed?

**Comment by hyperpape** [comment]
Looks good. I think it can be closed.
